apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-a
  namespace: argocd
spec:
  project: app-a

  source:
    repoURL: https://github.com/sainarendrapanga04/argocd-example-apps.git
    targetRevision: master
    path: 'app-a/appsets'

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
