apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-project
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/sainarendrapanga04/argocd-example-apps.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: ns1
    - server: https://kubernetes.default.svc
      namespace: ns2
    - server: https://kubernetes.default.svc
      namespace: prod-ns3

  clusterResourceWhitelist:
    - group: argoproj.io
      kind: ApplicationSet
    - group: "*"
      kind: "*"
