apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-a
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Project for app-a

  sourceRepos:
    - https://github.com/sainarendrapanga04/argocd-example-apps.git

  destinations:
    # Parent / control apps
    - namespace: argocd
      server: https://kubernetes.default.svc

    # Workload namespaces
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: stg
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
