apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: app1
          - app: app2

  template:
    metadata:
      name: dev-{{app}}
    spec:
      project: default
      source:
        repoURL: https://github.com/sainarendrapanga04/app-gitops.git
        targetRevision: main
        path: apps/{{app}}
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
