apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: app1
            path: guestbook
            namespace: prod-ns1
          - app: app2
            path: guestbook
            namespace: prod-ns2

  template:
    metadata:
      name: '{{app}}-prod'
    spec:
      project: platform-project
      source:
        repoURL: https://github.com/sainarendrapanga04/argocd-example-apps.git
        targetRevision: master
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
