apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: app1
            path: guestbook
          - app: app2
            path: guestbook

  template:
    metadata:
      name: '{{app}}-prod'
    spec:
      project: platform-project
      source:
        repoURL: https://github.com/sainarendrapanga04/argocd-example-apps.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://prod-cluster
        namespace: ns3
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
